# Reset exisintg cluster
## If below variable is set to true then entire exiting cluster config will be deleted
reset_cluster: true

#Proxy server
proxy_setup: false

#Configure below proxy configs      when: {{ proxy_setup }} is set to True

#proxy_server: "http://web-proxy.server.net:8080"
#proxy_env:
#  http_proxy: http://web-proxy.server.net:8080
#  https_proxy: http://web-proxy.server.net:8080
#  no_proxy: <localnet_IP>,localhost


# Kubernetes
reset_cluster: true
kube_version: v1.14.2
token: yd6643.0xuwzrquyhh6cjj1
pod_network_cidr: 10.244.0.0/16

master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4'].address | default(groups['master'][0]) }}"
